// Generated by view binder compiler. Do not edit!
package com.example.locationdetail.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.cardview.widget.CardView;
import androidx.constraintlayout.widget.ConstraintLayout;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.example.locationdetail.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class LocationlistviewBinding implements ViewBinding {
  @NonNull
  private final ConstraintLayout rootView;

  @NonNull
  public final TextView addressValue;

  @NonNull
  public final CardView cardView;

  @NonNull
  public final TextView countyrValue;

  @NonNull
  public final TextView latitudeValue;

  @NonNull
  public final TextView localityValue;

  @NonNull
  public final TextView longitudeValue;

  @NonNull
  public final TextView tvAddress;

  @NonNull
  public final TextView tvCountryName;

  @NonNull
  public final TextView tvLatitude;

  @NonNull
  public final TextView tvLocality;

  @NonNull
  public final TextView tvLongitude;

  private LocationlistviewBinding(@NonNull ConstraintLayout rootView,
      @NonNull TextView addressValue, @NonNull CardView cardView, @NonNull TextView countyrValue,
      @NonNull TextView latitudeValue, @NonNull TextView localityValue,
      @NonNull TextView longitudeValue, @NonNull TextView tvAddress,
      @NonNull TextView tvCountryName, @NonNull TextView tvLatitude, @NonNull TextView tvLocality,
      @NonNull TextView tvLongitude) {
    this.rootView = rootView;
    this.addressValue = addressValue;
    this.cardView = cardView;
    this.countyrValue = countyrValue;
    this.latitudeValue = latitudeValue;
    this.localityValue = localityValue;
    this.longitudeValue = longitudeValue;
    this.tvAddress = tvAddress;
    this.tvCountryName = tvCountryName;
    this.tvLatitude = tvLatitude;
    this.tvLocality = tvLocality;
    this.tvLongitude = tvLongitude;
  }

  @Override
  @NonNull
  public ConstraintLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static LocationlistviewBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static LocationlistviewBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.locationlistview, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static LocationlistviewBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.address_value;
      TextView addressValue = ViewBindings.findChildViewById(rootView, id);
      if (addressValue == null) {
        break missingId;
      }

      id = R.id.cardView;
      CardView cardView = ViewBindings.findChildViewById(rootView, id);
      if (cardView == null) {
        break missingId;
      }

      id = R.id.countyr_value;
      TextView countyrValue = ViewBindings.findChildViewById(rootView, id);
      if (countyrValue == null) {
        break missingId;
      }

      id = R.id.latitude_value;
      TextView latitudeValue = ViewBindings.findChildViewById(rootView, id);
      if (latitudeValue == null) {
        break missingId;
      }

      id = R.id.locality_value;
      TextView localityValue = ViewBindings.findChildViewById(rootView, id);
      if (localityValue == null) {
        break missingId;
      }

      id = R.id.longitude_value;
      TextView longitudeValue = ViewBindings.findChildViewById(rootView, id);
      if (longitudeValue == null) {
        break missingId;
      }

      id = R.id.tv_address;
      TextView tvAddress = ViewBindings.findChildViewById(rootView, id);
      if (tvAddress == null) {
        break missingId;
      }

      id = R.id.tv_Country_name;
      TextView tvCountryName = ViewBindings.findChildViewById(rootView, id);
      if (tvCountryName == null) {
        break missingId;
      }

      id = R.id.tv_latitude;
      TextView tvLatitude = ViewBindings.findChildViewById(rootView, id);
      if (tvLatitude == null) {
        break missingId;
      }

      id = R.id.tv_locality;
      TextView tvLocality = ViewBindings.findChildViewById(rootView, id);
      if (tvLocality == null) {
        break missingId;
      }

      id = R.id.tv_longitude;
      TextView tvLongitude = ViewBindings.findChildViewById(rootView, id);
      if (tvLongitude == null) {
        break missingId;
      }

      return new LocationlistviewBinding((ConstraintLayout) rootView, addressValue, cardView,
          countyrValue, latitudeValue, localityValue, longitudeValue, tvAddress, tvCountryName,
          tvLatitude, tvLocality, tvLongitude);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
